#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2022-2026 Daniel Pęcak
"""
Generates the BSk31 golden-master file ``tests/golden/bsk31.json``.

Usage (from the repository root):

    python -m tests.golden.make_golden            # report which cases would change
    python -m tests.golden.make_golden --write    # (re)write the golden file

Regenerate only for an intentional change of the numbers (e.g. a physics fix) and say
why in the commit message; a pure refactor must leave the file untouched.
"""
import argparse
import datetime
import json
import os
import subprocess

import numpy as np

import libnest
from tests.golden import spec

HERE = os.path.dirname(os.path.abspath(__file__))
PATH = os.path.join(HERE, spec.GOLDEN_FILE)


def _git_commit():
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=HERE,
                              capture_output=True, text=True, check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def generate():
    inputs = spec.make_inputs()
    return {
        "about": "Golden master for libnest BSk31 (TODO_edf.md, phase E0). "
                 "Generated by tests/golden/make_golden.py - do not edit by hand.",
        "generated": {"date": datetime.date.today().isoformat(),
                      "git_commit": _git_commit(),
                      "libnest": libnest.__version__,
                      "numpy": np.__version__},
        "inputs": {k: np.asarray(v, dtype=float).tolist() for k, v in inputs.items()},
        "api": {
            "functions": {m: spec.public_functions(m) for m in spec.API_FUNCTIONS},
            "constants": {m: {c: float(getattr(spec.resolve_module(m), c)) for c in names}
                          for m, names in spec.API_CONSTANTS.items()},
        },
        "cases": {name: dict(case, **spec.evaluate(case, inputs))
                  for name, case in spec.CASES.items()},
    }


def changed_cases(old, new):
    """Names of cases whose stored results differ (exact comparison)."""
    names = sorted(set(old.get("cases", {})) | set(new["cases"]))
    out = []
    for n in names:
        a, b = old.get("cases", {}).get(n), new["cases"].get(n)
        if a is None or b is None:
            out.append(n)
            continue
        if any(not np.array_equal(np.asarray(a.get(k), dtype=float),
                                  np.asarray(b.get(k), dtype=float), equal_nan=True)
               for k in ("array", "scalar")):
            out.append(n)
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("--write", action="store_true", help="write the golden file")
    opts = parser.parse_args()

    new = generate()
    if os.path.exists(PATH):
        with open(PATH) as f:
            old = json.load(f)
        diff = changed_cases(old, new)
        api_diff = old.get("api") != new["api"]
        print("{} case(s) differ from {}{}".format(
            len(diff), spec.GOLDEN_FILE, ":" if diff else "."))
        for n in diff:
            print("  ", n)
        if api_diff:
            print("The public API snapshot differs.")
    else:
        print("{} does not exist yet.".format(spec.GOLDEN_FILE))

    if opts.write:
        with open(PATH, "w") as f:
            json.dump(new, f, indent=1)
            f.write("\n")
        print("Wrote", PATH)
    else:
        print("Nothing written (use --write).")


if __name__ == "__main__":
    main()
