name: Main
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build 
      uses: ammaraskar/sphinx-action@0.4
      with:
        # The folder containing your sphinx docs.
        docs-folder: './docs/source'
        # The command used to build your documentation.
        build-command: 'make html'# optional, default is make html
